// Copyright © 2021 Balazs Perlaki-Horvath, PerlakiDigital. All rights reserved.

import Foundation
import RxSwift

struct WebServiceLocal: WebService {
    
    let decoder = JSONDecoder()
    
    func categories() -> Observable<[Category]> {
        let s: String = """
        [
            {
                "id": 41,
                "name": "Animals"
            },
            {
                "id": 35,
                "name": "Archaeology"
            },
            {
                "id": 1,
                "name": "Art"
            },
            {
                "id": 5,
                "name": "Autobiography"
            },
            {
                "id": 6,
                "name": "Biography"
            },
            {
                "id": 7,
                "name": "Business"
            },
            {
                "id": 53,
                "name": "Children"
            },
            {
                "id": 12,
                "name": "Childrens"
            },
            {
                "id": 9,
                "name": "Cuisine"
            },
            {
                "id": 8,
                "name": "Culture"
            },
            {
                "id": 51,
                "name": "Earth Sciences"
            },
            {
                "id": 10,
                "name": "Education"
            },
            {
                "id": 11,
                "name": "Fiction"
            },
            {
                "id": 13,
                "name": "Film"
            },
            {
                "id": 34,
                "name": "Gardens"
            },
            {
                "id": 14,
                "name": "Geology"
            },
            {
                "id": 33,
                "name": "Guide book/Reference book"
            },
            {
                "id": 43,
                "name": "Historical Fiction"
            },
            {
                "id": 2,
                "name": "History"
            },
            {
                "id": 15,
                "name": "History culture"
            },
            {
                "id": 17,
                "name": "Hobby"
            },
            {
                "id": 30,
                "name": "Holidays"
            },
            {
                "id": 45,
                "name": "Humanities"
            },
            {
                "id": 42,
                "name": "Humor"
            },
            {
                "id": 39,
                "name": "Irish Language"
            },
            {
                "id": 44,
                "name": "Journal"
            },
            {
                "id": 46,
                "name": "Language"
            },
            {
                "id": 48,
                "name": "Law"
            },
            {
                "id": 38,
                "name": "Lifestyle"
            },
            {
                "id": 47,
                "name": "Literature"
            },
            {
                "id": 49,
                "name": "Medicine"
            },
            {
                "id": 40,
                "name": "Memoir"
            },
            {
                "id": 18,
                "name": "Music"
            },
            {
                "id": 19,
                "name": "Non-fiction"
            },
            {
                "id": 20,
                "name": "Photography"
            },
            {
                "id": 29,
                "name": "Places to stay"
            },
            {
                "id": 21,
                "name": "Play"
            },
            {
                "id": 23,
                "name": "Poetry"
            },
            {
                "id": 24,
                "name": "Politics"
            },
            {
                "id": 37,
                "name": "Religion"
            },
            {
                "id": 50,
                "name": "Science"
            },
            {
                "id": 25,
                "name": "Society"
            },
            {
                "id": 27,
                "name": "Sports"
            },
            {
                "id": 52,
                "name": "Technology"
            },
            {
                "id": 28,
                "name": "Tourism"
            },
            {
                "id": 31,
                "name": "Travel"
            },
            {
                "id": 54,
                "name": "Unknown E"
            },
            {
                "id": 55,
                "name": "Unknown T"
            },
            {
                "id": 36,
                "name": "Young Adult/Teen"
            }
        ]
        """
        let categories: [Category] = try! decode(data: s.data(using: .utf8)!)
        return .just(categories)
    }
    
    func authors() -> Observable<[Author]> {
        let s: String = """
    {
        "response": [
            {
                "id": 24337,
                "firstname": "",
                "lastname": "   ",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_71106_00_20200430_00",
                "altlink": ""
            },
            {
                "id": 25087,
                "firstname": "Donal",
                "lastname": " Drisceoil",
                "dob": null,
                "profile": "",
                "contact": null,
                "address": null,
                "url": null,
                "image": null,
                "createdby": "/nielsen_xml/122370_77946_00_20201216_00.upd",
                "altlink": null
            },
            {
                "id": 25088,
                "firstname": "Diarmuid",
                "lastname": " Drisceoil",
                "dob": null,
                "profile": "",
                "contact": null,
                "address": null,
                "url": null,
                "image": null,
                "createdby": "/nielsen_xml/122370_77946_00_20201216_00.upd",
                "altlink": null
            },
            {
                "id": 1560,
                "firstname": "various",
                "lastname": "-",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": "",
                "createdby": "1",
                "altlink": ""
            },
            {
                "id": 23081,
                "firstname": "Moane",
                "lastname": ",Moane, G.",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_57280_00_20180622_00",
                "altlink": ""
            },
            {
                "id": 24919,
                "firstname": "Reidun",
                "lastname": "(Reidun's Harp Centre)",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_75746_01_20201012_00",
                "altlink": ""
            },
            {
                "id": 23574,
                "firstname": "",
                "lastname": "***",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_64270_01_20190328_00",
                "altlink": ""
            },
            {
                "id": 16702,
                "firstname": "MAHON",
                "lastname": "A",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_01_20161018_01.add",
                "altlink": ""
            },
            {
                "id": 23679,
                "firstname": "Coleman",
                "lastname": "A. Dennehy",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_65214_00_20190614_00",
                "altlink": ""
            },
            {
                "id": 17695,
                "firstname": "",
                "lastname": "A& L Goodbody Solicitors",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_01_20161018_01.add",
                "altlink": ""
            },
            {
                "id": 22449,
                "firstname": "",
                "lastname": "A&L Goodbody",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_51424_01_20170911_00",
                "altlink": ""
            },
            {
                "id": 5112,
                "firstname": "F.H.A.",
                "lastname": "Aalen",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_00_20161018_00.add",
                "altlink": ""
            },
            {
                "id": 24960,
                "firstname": "",
                "lastname": "Aaron Edwards",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_75906_00_20201016_00",
                "altlink": ""
            },
            {
                "id": 24206,
                "firstname": "Marja",
                "lastname": "Aartsen",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_69786_00_20200312_00",
                "altlink": ""
            },
            {
                "id": 22100,
                "firstname": "Erdal",
                "lastname": "Abaci",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_50176_01_20170303_00",
                "altlink": ""
            },
            {
                "id": 3725,
                "firstname": "Vivienne",
                "lastname": "Abbott",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_00_20161018_00.add",
                "altlink": ""
            },
            {
                "id": 19241,
                "firstname": "Richard",
                "lastname": "Abbott",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_01_20161018_02.add",
                "altlink": ""
            },
            {
                "id": 2255,
                "firstname": "Annabel",
                "lastname": "Abbs",
                "dob": "0000-00-00",
                "profile": "Annabel Abbs grew up in Wales and Sussex, with stints in Dorset, Bristol and Hereford. She has a degree in English Literature from the University of East Anglia and a Masters in Marketing and Statistics from the University of Kingston. After fifteen years running a consultancy, she took a career break to bring up her four children, before returning to her first love, literature.",
                "contact": "",
                "address": "",
                "url": "http://www.annabelabbs.com/",
                "image": "author2255.png",
                "createdby": "1",
                "altlink": "https://twitter.com/annabelabbs"
            },
            {
                "id": 22966,
                "firstname": "Yoshi",
                "lastname": "Abe",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_56360_00_20180521_00",
                "altlink": ""
            },
            {
                "id": 17026,
                "firstname": "Michael",
                "lastname": "Abecassis",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_01_20161018_01.add",
                "altlink": ""
            },
            {
                "id": 2867,
                "firstname": "Nick",
                "lastname": "Abel",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_00_20161018_00.add",
                "altlink": ""
            },
            {
                "id": 20443,
                "firstname": "Anthony M.",
                "lastname": "Abela",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_01_20161018_03.add",
                "altlink": ""
            },
            {
                "id": 23461,
                "firstname": "Alan",
                "lastname": "Abernathy",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_63370_00_20190115_00",
                "altlink": ""
            },
            {
                "id": 13358,
                "firstname": "Alan",
                "lastname": "Abernethy",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_00_20161018_03.add",
                "altlink": ""
            },
            {
                "id": 23897,
                "firstname": "Daniel Aboye",
                "lastname": "Aberra",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_66802_00_20191014_00",
                "altlink": ""
            },
            {
                "id": 3956,
                "firstname": "Kevin",
                "lastname": "Abosch",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_00_20161018_00.add",
                "altlink": ""
            },
            {
                "id": 24588,
                "firstname": "Daniel",
                "lastname": "Aboye Aberra",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "/nielsen_xml/122370_73546_00_20200727_00",
                "altlink": ""
            },
            {
                "id": 13114,
                "firstname": "William",
                "lastname": "Abrahamson",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_00_20161018_03.add",
                "altlink": ""
            },
            {
                "id": 15114,
                "firstname": "Harold J.",
                "lastname": "Abramson",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_01_20161018_00.add",
                "altlink": ""
            },
            {
                "id": 6312,
                "firstname": "Mike",
                "lastname": "Absalom",
                "dob": "0000-00-00",
                "profile": "",
                "contact": "",
                "address": "",
                "url": "",
                "image": null,
                "createdby": "122370_49204_00_20161018_01.add",
                "altlink": ""
            }
        ],
        "token": null
    }
"""
        let response: ResponseAuthors = try! JSONDecoder().decode(ResponseAuthors.self, from: s.data(using: .utf8)!)
        
        let authors: Observable<[Author]> = .just(response.response.sorted(by: { (a: Author, b: Author) in
            a.fullName <= b.fullName
        }))
        return authors
    }
    
    func latestBooks(page: Int) -> Observable<[Book]> {
        let s: String = """
        {
            "response": [
                {
                    "title": "'Lonely Planet Pocket Los Angeles<br>6th ed.'",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / United States / West / General; Western & Pacific Coast states; Travel and holiday guides; US West: Pacific States; US West; Travel & Holiday Guides: General; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50702,
                    "lastupdated": "2020-12-22 00:00:00",
                    "published": "2021-07-09",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 192,
                    "isbn13": "9781786571021",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78066_01_20201221_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Kilmichael: The Ambush and Its Afterlife'",
                    "author": "Eve Morrison",
                    "authorid": 24474,
                    "publisher": "Irish Academic Press Ltd",
                    "publisherurl": "",
                    "genre": "Humanities",
                    "categoryid": 45,
                    "area": "HISTORY / Europe / General; HISTORY / Military / General; HISTORY / Modern / 20th Century; European history; Military history; 20th century history: c 1900 to c 2000; 20th century; European history; Military history; 20th century, c 1900 to c 1999; 1916-1922 (Irish Revolutionary period); ANF: Histo",
                    "synopsis": "''",
                    "id": 50608,
                    "lastupdated": "2020-12-11 00:00:00",
                    "published": "2021-06-14",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 0,
                    "ebook": 1,
                    "audio": 0,
                    "pages": 300,
                    "isbn13": "9781788551472",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77746_01_20201210_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Kilmichael: The Ambush and Its Afterlife'",
                    "author": "Eve Morrison",
                    "authorid": 24474,
                    "publisher": "Irish Academic Press Ltd",
                    "publisherurl": "",
                    "genre": "Humanities",
                    "categoryid": 45,
                    "area": "HISTORY / Europe / General; HISTORY / Military / General; HISTORY / Modern / 20th Century; European history; Military history; 20th century history: c 1900 to c 2000; 20th century; European history; Military history; 20th century, c 1900 to c 1999; 1916-1922 (Irish Revolutionary period); ANF: Histo",
                    "synopsis": "''",
                    "id": 50609,
                    "lastupdated": "2020-12-11 00:00:00",
                    "published": "2021-06-14",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 0,
                    "ebook": 1,
                    "audio": 0,
                    "pages": 300,
                    "isbn13": "9781788551489",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77746_01_20201210_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'The Snag List'",
                    "author": "Sophie  White",
                    "authorid": 2342,
                    "publisher": "Hachette Books Ireland",
                    "publisherurl": "",
                    "genre": "Fiction",
                    "categoryid": 11,
                    "area": "FICTION / Women; FICTION / Friendship; Modern & contemporary fiction; AF: General Fiction; ",
                    "synopsis": "'Sophie White grew up in Dublin and has a first class honours degree in Fine Art from the National College of Art and Design. \nAfter moving to New Zealand in her early 20s, Sophie went on to train as a chef while there and worked in the French Alps for several years before returning to Dublin in 2012.\nSophie began her writing career at age 27, when she started writing a weekly column 'The Domestic' for Sunday Independent's Life magazine. After the birth of her first child, she became a full-time writer, penning reviews of books and restaurants, cultural commentary and interviews for a variety of Irish publications and her first book Recipes for a Nervous Breakdown, part-memoir/part cookery book was published in 2016. \nMother of Pod, the successful podcast she hosts with Jen O'Dwyer, was launched in January 2018 and they launched a second podcast, The Creep Dive, in January 2019.\nSophie lives in Dublin with her husband and two sons. Filter This is her first novel.<br>'",
                    "id": 49506,
                    "lastupdated": "2020-06-16 00:00:00",
                    "published": "2021-06-11",
                    "image": "",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 320,
                    "isbn13": "9781529352702",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_72346_00_20200615_00",
                    "updated_by": "",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": "1529352703",
                    "US_ASIN": null
                },
                {
                    "title": "'Lonely Planet Andalucia<br>10th ed.'",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / Europe / Western; Western Continental Europe; Southern Europe; Travel and holiday guides; Spain; Portugal; Western Europe; Travel & Holiday Guides: General; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50679,
                    "lastupdated": "2020-12-22 00:00:00",
                    "published": "2021-06-11",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 384,
                    "isbn13": "9781787015210",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78066_00_20201221_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Lonely Planet Madrid<br>10th ed.'",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / Europe / Western; Western Continental Europe; Southern Europe; Travel and holiday guides; Spain; Portugal; Western Europe; Travel & Holiday Guides: General; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50701,
                    "lastupdated": "2020-12-22 00:00:00",
                    "published": "2021-06-11",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 256,
                    "isbn13": "9781787017092",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78066_01_20201221_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "The Book Club",
                    "author": "Roisin Meaney",
                    "authorid": 733,
                    "publisher": "Hachette Books Ireland",
                    "publisherurl": "",
                    "genre": "Fiction",
                    "categoryid": 11,
                    "area": "Romance; Modern & contemporary fiction; AF: General Fiction; ",
                    "synopsis": "'Roisin Meaney was born in Listowel, Co Kerry, She has lived in the US, Canada, Africa and Europe but is now based in Limerick, Ireland. This Number One bestselling author is a consistent presence on the Irish bestseller list and she is the author of fifteen novels including three stand alone novels set in the fictional island off the west coast of Ireland: One Summer, After the Wedding and I'll Be Home for Christmas. Her other bestsellers include: The Last Week of May, The People Next Door, Half Seven on a Thursday, Love in the Making, The Things We Do For Love, Something in Common, Two Fridays in April, The Reunion and The Anniversary. \n\nShe has also written books for children. Connect with Roisin Meaney on \n@roisinmeaney\nwww.roisinmeaney.com<br>'",
                    "id": 49545,
                    "lastupdated": "2020-06-30 00:00:00",
                    "published": "2021-06-10",
                    "image": "49545.jpg",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 320,
                    "isbn13": "9781529355642",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_72746_01_20200629_00",
                    "updated_by": "/nielsen_xml/122370_77986_01_20201217_00.upd",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "The Year of Lost and Found",
                    "author": "Felicity Hayes-McCoy",
                    "authorid": 1594,
                    "publisher": "Hachette Books Ireland",
                    "publisherurl": "",
                    "genre": "Fiction",
                    "categoryid": 11,
                    "area": "FICTION / Friendship; The countryside, country life; Modern & contemporary fiction; AF: General Fict",
                    "synopsis": "'Felicity Hayes-McCoy, author of the best-selling Finfarran series, was born in Dublin, Ireland. She studied literature at UCD before moving to England in the 1970s to train as an actress. Her work as a writer ranges from TV and radio drama and documentary, to screenplays, music theatre, memoir and children's books. Her Finfarran novels are widely read on both sides of the Atlantic, and in Australia, and have been translated into six languages. \nShe and her husband, opera director Wilf Judd, live in the West Kerry Gaeltacht and in Bermondsey, London. She blogs about life in both places on her website www.felicityhayesmccoy.co.uk and you can follow her on Twitter @fhayesmccoy and on Facebook at Felicity Hayes-McCoy Author.<br>'",
                    "id": 49452,
                    "lastupdated": "2020-06-05 00:00:00",
                    "published": "2021-06-03",
                    "image": "",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 320,
                    "isbn13": "9781529361056",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_72066_00_20200604_00",
                    "updated_by": "/nielsen_xml/122370_74666_00_20200904_00",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'The Estate'",
                    "author": "Liza Costello",
                    "authorid": 24495,
                    "publisher": "Hachette Books Ireland",
                    "publisherurl": "",
                    "genre": "Fiction",
                    "categoryid": 11,
                    "area": "Psychological thriller; AF: Thriller; ",
                    "synopsis": "''",
                    "id": 49461,
                    "lastupdated": "2020-06-05 00:00:00",
                    "published": "2021-06-03",
                    "image": "",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 320,
                    "isbn13": "9781529350111",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_72066_01_20200604_00",
                    "updated_by": "",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "What is Beautiful in the Sky: A book about endings and beginnings",
                    "author": "Michael Harding",
                    "authorid": 10776,
                    "publisher": "Hachette Books Ireland",
                    "publisherurl": "",
                    "genre": "Biography",
                    "categoryid": 6,
                    "area": "FAMILY & RELATIONSHIPS / Friendship; TRAVEL / Europe / Ireland; PSYCHOLOGY / Mental Health; Memoirs;",
                    "synopsis": "'Michael Harding is an author and playwright. His creative chronicle of ordinary life in the Irish midlands is published as a weekly column in The Irish Times. He has written numerous plays for the Abbey Theatre, including Una Pooka,Misogynist and Sour Grapes, and has published three novels, Priest, The Trouble with Sarah Gullion and Bird in the Snow as well as three bestselling memoirs, Staring at Lakes, which won three BGE Irish Book awards, Hanging with the Elephant and Talking to Strangers and the bestselling On Tuesdays I'm a Buddhist.<br>'",
                    "id": 49462,
                    "lastupdated": "2020-06-05 00:00:00",
                    "published": "2021-06-03",
                    "image": "",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 304,
                    "isbn13": "9781473691025",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_72066_01_20200604_00",
                    "updated_by": "/nielsen_xml/122370_74146_01_20200817_00",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'A Hut at the Edge of the Village'",
                    "author": "John Moriarty",
                    "authorid": 4390,
                    "publisher": "The Lilliput Press Ltd",
                    "publisherurl": "",
                    "genre": "Humanities",
                    "categoryid": 45,
                    "area": "The environment; ANF: Philosophy; ",
                    "synopsis": "'In this small book of big thoughts, award-winning author, mythologist and storyteller Martin Shaw situates Moriarty's work with respect to our eco-conscious era and a readership seeking spiritual and philosophical guidance.<br>There is a radical agency in John Moriarty's work that we as readers don't always spot. As our heads spin with mythological cross-referencing, poetical leaps and the philosophical bent, it is clear that there is nothing domestic, nothing tame, about John Moriarty. The power of Moriarty is that he has found a thousand beautiful ways to say something very disturbing: we have to change our lives.\nIn this small book of big thoughts, award-winning author, mythologist and storyteller Martin Shaw situates Moriarty's work with respect to our eco-conscious era and a readership seeking spiritual and philosophical guidance. Moriarty asks of us only one thing - that we move our gaze from seeing to beholding. And there the trouble begins, when we realize there is a world beyond us far bigger than our temporary ambitions.\nA Hut at the Edge of the Village presents a collection of Moriarty's writings ordered thematically, with sections ranging from place, love and wildness through to voyaging, ceremony and the legitimacy of sorrow. These carefully chosen extracts are supported by an introduction by Martin Shaw and foreword by Tommy Tiernan, a long-time admirer of Moriarty's work.\nAccording to Shaw, 'These are not pastoral times we are living in, but prophetic. We are at a moment when the world as we understand it has been turned upside down. The challenge is that there are fewer and fewer people who can interpret such happenings in a deep, soulful way. Moriarty can do that. When culture is in woeful crisis, the insights never come from parliament, senate, or committee; they come from the hut at the edge of the village. Let's go there. There is tremendous, unexpected hope waiting.'<br>John Moriarty (1938-2007) was born in Kerry and taught English literature a",
                    "id": 50292,
                    "lastupdated": "2020-10-19 00:00:00",
                    "published": "2021-06-01",
                    "image": "",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 128,
                    "isbn13": "9781843518006",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_75906_00_20201016_00",
                    "updated_by": "",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "Lonely Planet California's Best Trips<br>4th edition",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / Food, Lodging & Transportation / Road Travel; TRAVEL / United States / West / General; California; Travel guides: routes and ways; California; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50597,
                    "lastupdated": "2020-12-09 00:00:00",
                    "published": "2021-06-01",
                    "image": "50597.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 384,
                    "isbn13": "9781787013506",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77586_00_20201207_00.add",
                    "updated_by": "/nielsen_xml/122370_78186_00_20201229_00.upd",
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "Lonely Planet Florida<br>9th New edition",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / United States / South / General; TRAVEL / United States / General; Florida; Travel and holiday guides; Florida; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50599,
                    "lastupdated": "2020-12-09 00:00:00",
                    "published": "2021-06-01",
                    "image": "50599.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 544,
                    "isbn13": "9781787015692",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77586_01_20201207_00.add",
                    "updated_by": "/nielsen_xml/122370_78066_01_20201221_00.upd",
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "Lonely Planet California<br>9th New edition",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / United States / West / General; TRAVEL / United States / General; California; Travel and holiday guides; California; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50600,
                    "lastupdated": "2020-12-09 00:00:00",
                    "published": "2021-06-01",
                    "image": "50600.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 800,
                    "isbn13": "9781787016699",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77586_01_20201207_00.add",
                    "updated_by": "/nielsen_xml/122370_78066_01_20201221_00.upd",
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "Lonely Planet Miami & the Keys<br>9th New edition",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / United States / South / General; TRAVEL / United States / General; Florida; Travel and holiday guides; Miami; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50601,
                    "lastupdated": "2020-12-09 00:00:00",
                    "published": "2021-06-01",
                    "image": "50601.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 256,
                    "isbn13": "9781787017177",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77586_01_20201207_00.add",
                    "updated_by": "/nielsen_xml/122370_78066_01_20201221_00.upd",
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "Lonely Planet USA's Best Trips<br>4th edition",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / Food, Lodging & Transportation / Road Travel; TRAVEL / Reference; USA; Travel guides: routes and ways; United States of America, USA; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50611,
                    "lastupdated": "2020-12-15 00:00:00",
                    "published": "2021-06-01",
                    "image": "50611.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 672,
                    "isbn13": "9781787017894",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77826_00_20201214_00.add",
                    "updated_by": "/nielsen_xml/122370_78186_00_20201229_00.upd",
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "Lonely Planet Great Britain's Best Trips<br>2nd New edition",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / Food, Lodging & Transportation / Road Travel; TRAVEL / Special Interest / General; United Kingdom, Great Britain; Travel guides: routes and ways; United Kingdom, Great Britain; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50621,
                    "lastupdated": "2020-12-15 00:00:00",
                    "published": "2021-06-01",
                    "image": "50621.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 448,
                    "isbn13": "9781786576286",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77826_01_20201214_00.add",
                    "updated_by": "/nielsen_xml/122370_78066_01_20201221_00.upd",
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "Lonely Planet Best of California<br>2nd New edition",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / United States / West / General; TRAVEL / United States / General; California; Travel and holiday guides; California; ANF: Travel Guides; ",
                    "synopsis": "''",
                    "id": 50622,
                    "lastupdated": "2020-12-15 00:00:00",
                    "published": "2021-06-01",
                    "image": "50622.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 324,
                    "isbn13": "9781787015333",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77826_01_20201214_00.add",
                    "updated_by": "/nielsen_xml/122370_78066_01_20201221_00.upd",
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Country House Collections: Past, Present and Future'",
                    "author": "Terence Dooley",
                    "authorid": 9536,
                    "publisher": "Four Courts Press Ltd",
                    "publisherurl": "",
                    "genre": "Humanities",
                    "categoryid": 45,
                    "area": "Modern history to 20th century: c 1700 to c 1900; Social & cultural history; Family history, tracing ancestors; ANF: History; ",
                    "synopsis": "''",
                    "id": 50714,
                    "lastupdated": "2020-12-23 00:00:00",
                    "published": "2021-05-28",
                    "image": "50714.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 1,
                    "paperback": 0,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 288,
                    "isbn13": "9781846829758",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78106_01_20201222_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'The early residential buildings of Trinity College Dublin: Architecture, financing, people'",
                    "author": "R.A. Somerville",
                    "authorid": 25119,
                    "publisher": "Four Courts Press Ltd",
                    "publisherurl": "",
                    "genre": "Humanities",
                    "categoryid": 45,
                    "area": "History of architecture; Modern history to 20th century: c 1700 to c 1900; History of engineering & technology; Ireland; For Post-Leaving Certificate (Irish); ANF: History; ",
                    "synopsis": "''",
                    "id": 50715,
                    "lastupdated": "2020-12-23 00:00:00",
                    "published": "2021-05-28",
                    "image": "50715.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 1,
                    "paperback": 0,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 288,
                    "isbn13": "9781846829680",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78106_01_20201222_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'The Wildflowers of Ireland: A Field Guide'",
                    "author": "Zoe Devlin",
                    "authorid": 9106,
                    "publisher": "Gill",
                    "publisherurl": "https://www.gillbooks.ie/",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "REFERENCE / General; SCIENCE / Life Sciences / Botany; NATURE / General; Reference works; Botany & plant sciences; Natural history; Western Continental Europe; Trees, wildflowers and plants: general interest; Nature and the natural world: general interest; Reference works; Botany and plant sciences",
                    "synopsis": "'New and updated edition of Ireland's bestselling wildflower guide.<br>Discover the fascinating world of Ireland's diverse and astonishing collection of native wildflowers. This new edition reflects the many changes to our botanical knowledge since The Wildflowers of Ireland was first published in 2014. There's updated information on the distribution of native wildflowers, along with more than 90 additional species, all beautifully photographed by the author.\n\n\n\nFor ease of identification, the species are divided into colour categories and within each category the species are grouped by, for example, the number of petals in the flower or whether the species carries its flowers in a cluster or a spike.\n\n\n\nIn easily understood terminology, focus is put on the main identifying features of each plant, by colour, size, shape of flower, leaf, habitat, flowering season, and where in Ireland it might be found.\n\n\n\nThis is a must for enthusiasts of all ages and levels of experience.<br>Zoe Devlin is passionate about wildflowers and the environment. She combined her interests in botany and photography to develop the website, wildflowersofIreland.net. Zoe earnestly hopes this guide will encourage many, especially young people, to identify, understand and cherish wildflowers growing all around, if only they stop and look.<br>'",
                    "id": 50719,
                    "lastupdated": "2020-12-24 00:00:00",
                    "published": "2021-05-28",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 288,
                    "isbn13": "9780717191871",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78146_01_20201223_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Jump Start: Your journey of discovery to find true meaning and contentment'",
                    "author": "Daniella Moyles",
                    "authorid": 25105,
                    "publisher": "Gill",
                    "publisherurl": "https://www.gillbooks.ie/",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "BIOGRAPHY & AUTOBIOGRAPHY / Personal Memoirs; LITERARY COLLECTIONS / Letters; LITERARY COLLECTIONS / Diaries & Journals; BODY, MIND & SPIRIT / General; SELF-HELP / Personal Growth / General; Diaries, letters & journals; Mind, Body, Spirit: thought & practice; Popular psychology; Self-help, personal",
                    "synopsis": "'Start your own journey of discovery from the girl who's cracked it! The new journal and workbook from the author of the bestselling millenial burnout memoir, Jump:One Girl's Search for Meaning.<br>Daniella Moyle's memoir Jump: One Girl's Search for Meaning was an instant bestseller. She was widely praised for her honesty and openness about her experience of burnout and anxiety, of how her quest to have it all left her with a life that felt empty and meaningless, and how she recovered by taking time out to look at who she really was and uncover whose expectations she was trying to fulfil.\n\n\n\nIf you too are struggling to find meaning, build better relationships, or if you simply want to live your one precious life with more purpose, Jump Start is here to help. Daniella combines her own experience and training in psychology to help you take your own journey of self-compassion, discovery and growth so you can find your true purpose and a life of fulfilment and contentment.<br>Daniella Moyles is a certified yoga and meditation teacher. She previously worked as a model and radio presenter before packing it all in to backpack around the globe solo for two years. She has a higher diploma in nutritional science and lifestyle medicine, is currently undertaking a degree to become a psychotherapist, and is the founder of the STLL, a holistic-living and wellness business.<br>'",
                    "id": 50664,
                    "lastupdated": "2020-12-21 00:00:00",
                    "published": "2021-05-21",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 304,
                    "isbn13": "9780717191093",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78026_01_20201218_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'A history of the Irish pharmaceutical industry: Making medicines for the World'",
                    "author": "Pat McCarthy",
                    "authorid": 16068,
                    "publisher": "Four Courts Press Ltd",
                    "publisherurl": "",
                    "genre": "Humanities",
                    "categoryid": 45,
                    "area": "20th century history: c 1900 to c 2000; 21st century history: from c 2000 -; Regulation of medicines & medical devices; ANF: History; ",
                    "synopsis": "''",
                    "id": 50712,
                    "lastupdated": "2020-12-23 00:00:00",
                    "published": "2021-05-14",
                    "image": "50712.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 1,
                    "paperback": 0,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 256,
                    "isbn13": "9781846829796",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78106_00_20201222_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Awaken Your Power Within: Let Go of Fear. Discover Your Infinite Potential. Become Your True Self.'",
                    "author": "Gerry Hussey",
                    "authorid": 25081,
                    "publisher": "Hachette Books Ireland",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "BODY, MIND & SPIRIT / Mindfulness & Meditation; Mind, Body, Spirit: thought & practice; Mind, body, spirit: thought and practice; Mind, body, spirit; ANF: Health and Wellbeing; ",
                    "synopsis": "'Awaken Your Power Within  is a powerful guide for all ages, one which takes the reader on a path of discovery to a deeper understanding of who we truly are and the limitless possibilities of which we are all capable.<br>Gerry Hussey, The Soul Coach, is Ireland's leading health and performance coach and founder of the incredible movement Soul Space.  Here in his first, ground-breaking book, Awaken Your Power Within, he brings us on an open, honest and mind-blowing human encounter that takes the reader inside the heart and mind of a young boy who dared to ask deeper questions about the mind and soul. \nWith amazing insights, life lessons, and powerful meditations Awaken Your Power Within unlocks the truths about how we experience the world and shows us how we can break free from unconscious, self-limiting beliefs, habits, emotions and thinking patterns to reshape and reclaim our inner world, enabling us to live as our truest and most powerful self.       \nFrom letting go of the fear of not being enough, to overcoming the dis-ease of distraction, to opening up to a deeper level of consciousness,  Awaken Your Power Within  is a powerful guide for all ages, one which takes the reader on a path of discovery to a deeper understanding of who we truly are and the limitless possibilities of which we are all capable. \n'You are an infinite being with infinite potential. All you need to do is open yourself to a new consciousness, a true vision of who you really are and awaken to the power within' Gerry Hussey<br>Awaken Your Power Within  is a powerful guide for all ages, one which takes the reader on a path of discovery to a deeper understanding of who we truly are and the limitless possibilities of which we are all capable.<br>'",
                    "id": 50630,
                    "lastupdated": "2020-12-16 00:00:00",
                    "published": "2021-05-13",
                    "image": "50630.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 288,
                    "isbn13": "9781529368888",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77866_00_20201215_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "The Summer We Were Friends",
                    "author": "Fiona O'Brien",
                    "authorid": 6135,
                    "publisher": "Hachette Books Ireland",
                    "publisherurl": "",
                    "genre": "Fiction",
                    "categoryid": 11,
                    "area": "Modern & contemporary fiction; AF: General Fiction; ",
                    "synopsis": "'Fiona O'Brien left an award winning career in advertising to write her first novel in 2002. She went on to publish bestselling novels including None of My Affair, No Reservations, Without Him and The Love Book. She lives in Sandymount, Dublin. You can find Fiona on Facebook.<br>'",
                    "id": 49528,
                    "lastupdated": "2020-06-29 00:00:00",
                    "published": "2021-05-06",
                    "image": "",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 320,
                    "isbn13": "9781529354157",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_72706_01_20200626_00",
                    "updated_by": "/nielsen_xml/122370_76466_01_20201103_00",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": "1529354153",
                    "US_ASIN": null
                },
                {
                    "title": "'Ireland's Pirate Trail: A Quest to Uncover Our Swashbuckling Past'",
                    "author": "Des Ekin",
                    "authorid": 13025,
                    "publisher": "O'Brien Press Ltd",
                    "publisherurl": "",
                    "genre": "Humanities",
                    "categoryid": 45,
                    "area": "HISTORY / Europe / Ireland; European history; ; Pirates - Ireland - History; Piracy - Ireland - History; Regional History; ANF: History; ",
                    "synopsis": "'Des Ekin embarks on a roadtrip around the entire coast of Ireland, in search of our piratical heritage, uncovering an amazing history of swashbuckling bandits, both Irish-born and imported.<br>Bloodthirsty buccaneers and buried treasure, fierce sea battles and cold-blooded murders, Barbary ducats and silver pieces of eight.\n\n\n\nDes Ekin embarks on a roadtrip around the entire coast of Ireland, in search of our piratical heritage, uncovering an amazing history of swashbuckling bandits, both Irish-born and imported.\n\n\n\nIreland's Pirate Trail tells stories of freebooters and pirates from every corner of our coast over a thousand years, including famous pirates like Anne Bonny and William Lamport, who set off to ply their trade in the Caribbean. Ekin also debunks many myths about our most well-known sea warrior, Granuaile, the 'Pirate Queen' of Mayo. Thoroughly researched and beautifully told. Filled with exciting untold stories.<br>Preface 11\n\nPart I\n\nEast by Sou'-East 17\n\n1. Pirate Pilgrimage the First 18\n\nDalkey, Tramore, New Ross, Dublin\n\nOn the Trail of McKinley's Gold 21\n\n2. Pirate Pilgrimage the Second 42\n\nCounty Meath\n\n'I'll Make You Officers ... in Hell.' 44\n\n3. Pirate Pilgrimage the Third 54\n\nWexford Town\n\nWilliam Lamport, the Wex-Mex 'Zorro' 56\n\n4. Pirate Pilgrimage the Fourth 66\n\nSaltees, Dublin City, Rush\n\nThe Three Privateers and the Rebel Yell from Rush 69\n\nPart II\n\nSouth by Sou'-West 91\n\n5. Pirate Pilgrimage the Fifth 92\n\nWaterford, Roaring Water Bay\n\n'He Led Them in a Carol, Then Clapped Them in Irons'95\n\n6. Pirate Pilgrimage the Sixth 105\n\nKinsale, Carolina, Caribbean\n\nAnne Bonny, Scourge of the Caribbean 108 \n\n7. Pirate Pilgrimage the Seventh 123\n\nCork City, Brazil, Boston\n\nThe Strange American Odyssey of Peter Roach 129\n\n8. Pirate Pilgrimage the Eighth 143\n\nBerehaven, Leamcon, Baltimore, Valentia Island\n\nThe Hellhounds of Dog's Leap and the \n\nPirate Armadas of West Cork 145\n\n9. Pirate Pilgrimage the Ninth 166\n\nCastleisland\n\nThe Framing of William Marsh169\n\nPart III\n\nWest by Nor'-West 189\n\n10. Pirate Pilgrimage the Tenth 190\n\nClare Island\n\nGrania Mania 194\n\n11. Pirate Pilgrimage the Eleventh 221\n\nBroad Haven\n\nThe Admiral, the Pirate, the Chieftain and his Daughters 225\n\n12. Pirate Pilgrimage the Twelfth 233\n\nKillybegs\n\n'Twenty Good Men Could Cut Their Throats' 237\n\n13. Pirate Pilgrimage the Thirteenth 251\n\nDunfanaghy, Achill Island\n\nThe World's Most Wanted Man 254\n\nPart IV\n\nNorth by Nor'-East 271\n\n14. Pirate Pilgrimage the Fourteenth 272\n\nPortrush\n\nBlack Tom, the Scummer of the Sea 275\n\n15. Pirate Pilgrimage the Fifteenth 283\n\nCarrickfergus\n\n'I Drew My Sword for the Rights of Men' 285\n\n16. Pirate Pilgrimage the Sixteenth 294\n\nBelfast, Holywood, Bangor, Donaghadee\n\nPirates and Belfast Lough 296\n\n17. Pirate Pilgrimage the Seventeenth 308\n\nRathlin, Inishowen, Howth, Strangford, Dublin\n\nT",
                    "id": 50612,
                    "lastupdated": "2020-12-15 00:00:00",
                    "published": "2021-05-03",
                    "image": "50612.jpg",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 0,
                    "ebook": 1,
                    "audio": 0,
                    "pages": 368,
                    "isbn13": "9781788492669",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77826_00_20201214_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Ireland's Pirate Trail: A Quest to Uncover Our Swashbuckling Past'",
                    "author": "Des Ekin",
                    "authorid": 13025,
                    "publisher": "O'Brien Press Ltd",
                    "publisherurl": "",
                    "genre": "Humanities",
                    "categoryid": 45,
                    "area": "HISTORY / Europe / Ireland; European history; ; Pirates - Ireland - History; Piracy - Ireland - History; Regional History; ANF: History; ",
                    "synopsis": "'Des Ekin embarks on a roadtrip around the entire coast of Ireland, in search of our piratical heritage, uncovering an amazing history of swashbuckling bandits, both Irish-born and imported.<br>Bloodthirsty buccaneers and buried treasure, fierce sea battles and cold-blooded murders, Barbary ducats and silver pieces of eight.\n\n\n\nDes Ekin embarks on a roadtrip around the entire coast of Ireland, in search of our piratical heritage, uncovering an amazing history of swashbuckling bandits, both Irish-born and imported.\n\n\n\nIreland's Pirate Trail tells stories of freebooters and pirates from every corner of our coast over a thousand years, including famous pirates like Anne Bonny and William Lamport, who set off to ply their trade in the Caribbean. Ekin also debunks many myths about our most well-known sea warrior, Granuaile, the 'Pirate Queen' of Mayo. Thoroughly researched and beautifully told. Filled with exciting untold stories.<br>Preface 11\n\nPart I\n\nEast by Sou'-East 17\n\n1. Pirate Pilgrimage the First 18\n\nDalkey, Tramore, New Ross, Dublin\n\nOn the Trail of McKinley's Gold 21\n\n2. Pirate Pilgrimage the Second 42\n\nCounty Meath\n\n'I'll Make You Officers ... in Hell.' 44\n\n3. Pirate Pilgrimage the Third 54\n\nWexford Town\n\nWilliam Lamport, the Wex-Mex 'Zorro' 56\n\n4. Pirate Pilgrimage the Fourth 66\n\nSaltees, Dublin City, Rush\n\nThe Three Privateers and the Rebel Yell from Rush 69\n\nPart II\n\nSouth by Sou'-West 91\n\n5. Pirate Pilgrimage the Fifth 92\n\nWaterford, Roaring Water Bay\n\n'He Led Them in a Carol, Then Clapped Them in Irons'95\n\n6. Pirate Pilgrimage the Sixth 105\n\nKinsale, Carolina, Caribbean\n\nAnne Bonny, Scourge of the Caribbean 108 \n\n7. Pirate Pilgrimage the Seventh 123\n\nCork City, Brazil, Boston\n\nThe Strange American Odyssey of Peter Roach 129\n\n8. Pirate Pilgrimage the Eighth 143\n\nBerehaven, Leamcon, Baltimore, Valentia Island\n\nThe Hellhounds of Dog's Leap and the \n\nPirate Armadas of West Cork 145\n\n9. Pirate Pilgrimage the Ninth 166\n\nCastleisland\n\nThe Framing of William Marsh169\n\nPart III\n\nWest by Nor'-West 189\n\n10. Pirate Pilgrimage the Tenth 190\n\nClare Island\n\nGrania Mania 194\n\n11. Pirate Pilgrimage the Eleventh 221\n\nBroad Haven\n\nThe Admiral, the Pirate, the Chieftain and his Daughters 225\n\n12. Pirate Pilgrimage the Twelfth 233\n\nKillybegs\n\n'Twenty Good Men Could Cut Their Throats' 237\n\n13. Pirate Pilgrimage the Thirteenth 251\n\nDunfanaghy, Achill Island\n\nThe World's Most Wanted Man 254\n\nPart IV\n\nNorth by Nor'-East 271\n\n14. Pirate Pilgrimage the Fourteenth 272\n\nPortrush\n\nBlack Tom, the Scummer of the Sea 275\n\n15. Pirate Pilgrimage the Fifteenth 283\n\nCarrickfergus\n\n'I Drew My Sword for the Rights of Men' 285\n\n16. Pirate Pilgrimage the Sixteenth 294\n\nBelfast, Holywood, Bangor, Donaghadee\n\nPirates and Belfast Lough 296\n\n17. Pirate Pilgrimage the Seventeenth 308\n\nRathlin, Inishowen, Howth, Strangford, Dublin\n\nT",
                    "id": 50623,
                    "lastupdated": "2020-12-15 00:00:00",
                    "published": "2021-05-03",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 368,
                    "isbn13": "9781788492454",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_77826_01_20201214_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "National Parks of America<br>2nd edition",
                    "author": "Lonely Planet",
                    "authorid": 23626,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "TRAVEL / Special Interest / General; TRAVEL / General; Places and peoples: general and pictorial wor",
                    "synopsis": "''",
                    "id": 50364,
                    "lastupdated": "2020-11-10 00:00:00",
                    "published": "2021-05-01",
                    "image": "50364.jpg",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 1,
                    "paperback": 0,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 344,
                    "isbn13": "9781838694494",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_76666_01_20201109_00",
                    "updated_by": "/nielsen_xml/122370_77826_01_20201214_00.upd",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Epic Hikes of Europe'",
                    "author": " Lonely Planet",
                    "authorid": 13396,
                    "publisher": "Lonely Planet Global Limited",
                    "publisherurl": "",
                    "genre": "Lifestyle",
                    "categoryid": 38,
                    "area": "SPORTS & RECREATION / Hiking; TRAVEL / Special Interest / Adventure; Europe; Walking, hiking, trekki",
                    "synopsis": "''",
                    "id": 50525,
                    "lastupdated": "2020-11-18 00:00:00",
                    "published": "2021-05-01",
                    "image": "",
                    "isbn": "",
                    "linktext": "",
                    "linkurl": "",
                    "vendor": "",
                    "vendorurl": "",
                    "hardback": 1,
                    "paperback": 0,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 320,
                    "isbn13": "9781838694289",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_76866_01_20201116_00",
                    "updated_by": "",
                    "size": null,
                    "editorschoice": "",
                    "narrative": "",
                    "UK_ASIN": null,
                    "US_ASIN": null
                },
                {
                    "title": "'Declan Kirby - GAA Star: Away Days'",
                    "author": "Michael Egan",
                    "authorid": 25103,
                    "publisher": "Gill",
                    "publisherurl": "https://www.gillbooks.ie/",
                    "genre": "Children",
                    "categoryid": 53,
                    "area": "YOUNG ADULT FICTION / Action & Adventure / General; YOUNG ADULT NONFICTION / Sports & Recreation / General; YOUNG ADULT NONFICTION / Family / General; Adventure stories (Children's / Teenage); Sports & outdoor recreation (Children's / Teenage); Personal & social issues: family issues (Children's / ",
                    "synopsis": "'An exciting new series of books for sports loving children.<br>Follow the trials and tribulations of Declan Kirby and his team at Smithgreen Gaelic football club, a recently formed but promising GAA team. Although they have a talented team, there are problems beneath the surface - will their temperamental star player Dereck produce the goods when it is really needed? Meanwhile, someone seems to be hatching a secret plan to have the manager replaced, just when they need him most.\n\n\n\nDeclan also carries a secret wish - that his dad will once again come and see him play. Maybe if they make the championship final his dream will come true?\n\n\n\nWritten by teacher and underage GAA coach Michael Egan, these exciting books are ideal for GAA loving children aged 7+.<br>Michael Egan has been a primary school teacher for over ten years and has coached several school GAA teams. He also set up Laois GAA TV, a website which shows highlights of important GAA club games within Laois.<br>'",
                    "id": 50653,
                    "lastupdated": "2020-12-21 00:00:00",
                    "published": "2021-04-30",
                    "image": "",
                    "isbn": null,
                    "linktext": null,
                    "linkurl": null,
                    "vendor": null,
                    "vendorurl": null,
                    "hardback": 0,
                    "paperback": 1,
                    "ebook": 0,
                    "audio": 0,
                    "pages": 160,
                    "isbn13": "9780717190508",
                    "asin": null,
                    "language": "",
                    "user_id": "/nielsen_xml/122370_78026_00_20201218_00.add",
                    "updated_by": null,
                    "size": null,
                    "editorschoice": null,
                    "narrative": null,
                    "UK_ASIN": null,
                    "US_ASIN": null
                }
            ],
            "token": null
        }
        """
        
        let response: ResponseBooks = try! JSONDecoder().decode(ResponseBooks.self, from: s.data(using: .utf8)!)
        return .just(response.response)
    }
    
    func countAuthors() -> Observable<Int> {
        .just(10)
    }
    
    func details(bookID: Int) -> Observable<BookDetails> {
        guard let url: URL = Bundle.main.url(forResource: "details", withExtension: "json") else { return .never() }
        let data = try! Data.init(contentsOf: url)
        let details: BookDetails = try! JSONDecoder().decode(BookDetails.self, from: data)
        return .just(details)
    }
    
    func booksBy(categoryId: Int) -> Observable<[Book]> {
        guard let url: URL = Bundle.main.url(forResource: "books_by_category", withExtension: "json") else { return .never() }
        let data = try! Data.init(contentsOf: url)
        let books: [Book] = try! JSONDecoder().decode([Book].self, from: data)
        return .just(books)
    }
}
